const MC = (() => {
  const q=(question,answer)=>({question,answer});
  const quiz=(question,choices,answer)=>({question,choices,answer});
  const L=(title, intuition, theory, math, example, practice, debug, realWorld, qa, matlab, check, visual='generic', video=null)=>({
    title,intuition,theory,math,example,practice,debug,realWorld,qa,matlab,check,visual,video
  });

  const stages=[
    {
      id:0,title:'Mathematics Refresher',short:'Math Refresher',level:'Refresh',icon:'Σ',
      description:'Rebuild only the mathematics you need for control, from algebra and complex numbers to matrices, eigenvalues, differential equations, and Laplace transforms.',
      lessons:[
        L('Algebra, Functions & Rearranging Equations',
          'Control equations become much easier when you can comfortably isolate a variable, factor a polynomial, and recognize a function. The goal is not advanced algebra. It is fluency.',
          'Review variables, functions, exponents, polynomial factoring, rational expressions, and solving simultaneous equations. Focus on recognizing the form of an equation before manipulating it.',
          'Example identities:  a(x+y)=ax+ay;  x²+bx+c=(x-r₁)(x-r₂);  if ax+b=c then x=(c-b)/a.',
          'Solve s²+4s+3=0. Factor it as (s+1)(s+3)=0, so the roots are s=-1 and s=-3. These roots later become poles of a control system.',
          'Factor s²+7s+12. Then solve 3x+2y=11 and x-y=1.',
          'Common mistake: changing the sign of only one term when moving an expression across the equals sign. Always perform the same operation on the entire side.',
          'A controller specification often gives an equation containing gain K. Rearranging it correctly lets you solve for the gain that meets a target error or pole location.',
          [q('Why do polynomial roots matter in control?','They often become system poles or zeros, which strongly influence stability and transient response.'),q('What is factoring?','Rewriting an expression as a product of simpler expressions.'),q('What is the safest way to rearrange an equation?','Apply the same algebraic operation to both sides and keep grouped terms together.')],
          'MATLAB: roots([1 4 3]) returns the roots of s²+4s+3.',
          quiz('What are the roots of s²+5s+6?',['-2 and -3','2 and 3','-1 and -6','0 and -5'],0),
          'roots'),
        L('Complex Numbers & the s-Plane',
          'Oscillation in control systems naturally leads to complex numbers. A complex pole is not an abstract nuisance. Its real part describes decay or growth, and its imaginary part describes oscillation.',
          'Use j=√(-1). A complex number is a+jb. Magnitude is √(a²+b²), angle is atan2(b,a), and the conjugate is a-jb.',
          '|a+jb|=√(a²+b²),   ∠(a+jb)=tan⁻¹(b/a).  For s=σ+jω, σ is the horizontal coordinate and ω the vertical coordinate.',
          'For s=-3+j4, magnitude=5. The pole lies in the left half-plane, so its exponential envelope decays while oscillating at a frequency related to 4 rad/s.',
          'Plot -2±j3, -5, and +1 on an s-plane. Label which are stable pole locations for a continuous-time LTI system.',
          'Common mistake: treating j² as +1. It is -1.',
          'Vehicle suspension and motor-speed systems often have underdamped modes represented by complex-conjugate poles.',
          [q('What does the real part of a pole indicate?','The exponential decay or growth rate.'),q('Why do complex poles usually occur in conjugate pairs?','Real-coefficient system equations produce conjugate roots.'),q('Where are stable continuous-time poles located?','In the open left half of the s-plane.')],
          "MATLAB: p=[-3+4j -3-4j]; plot(real(p),imag(p),'x'); grid on",
          quiz('For a continuous-time pole at +2-j3, what is the main concern?',['It is unstable because the real part is positive','It is stable because the imaginary part is negative','It is always critically damped','It has zero frequency'],0),
          'splane'),
        L('Vectors, Matrices & Matrix Arithmetic',
          'Modern control stores many first-order equations together using matrices. A matrix is simply an organized way to represent how states influence one another.',
          'Review row/column vectors, matrix dimensions, addition, scalar multiplication, matrix multiplication, transpose, and identity matrices. Matrix multiplication is order-sensitive.',
          'If A is m×n and B is n×p, then AB is m×p. In general AB≠BA.',
          'With A=[[0,1],[-3,-4]] and x=[x₁;x₂], Ax=[x₂;-3x₁-4x₂]. This compactly represents two coupled equations.',
          'Multiply [[1,2],[3,4]] by [5;6]. Then compute BA where possible and compare.',
          'Common mistake: multiplying corresponding entries instead of using row-by-column multiplication.',
          'A two-state mass-spring-damper model uses a 2×2 A matrix to describe how displacement and velocity evolve together.',
          [q('Why is matrix multiplication order important?','Because AB and BA generally represent different mappings and may even have different dimensions.'),q('What does I represent?','The identity matrix, which leaves a vector unchanged when multiplied compatibly.'),q('What does matrix dimension 2×3 mean?','Two rows and three columns.')],
          'MATLAB: A=[0 1;-3 -4]; x=[1;2]; A*x',
          quiz('If A is 2×3 and B is 3×4, what is the size of AB?',['2×4','3×3','4×2','Not defined'],0),
          'matrix'),
        L('Determinants, Inverses & Linear Equations',
          'Determinants help tell whether a square matrix is invertible. In control they appear in characteristic equations, eigenvalue calculations, and matrix inverses.',
          'For a 2×2 matrix [[a,b],[c,d]], det(A)=ad-bc. If det(A)≠0, A is invertible. Solving Ax=b can then use x=A⁻¹b, though numerical software often uses more stable methods.',
          'A⁻¹ = (1/det A)[[d,-b],[-c,a]] for a nonsingular 2×2 matrix.',
          'For A=[[2,1],[1,2]], det(A)=3 and A⁻¹=(1/3)[[2,-1],[-1,2]].',
          'Compute det([[4,2],[1,3]]) and solve Ax=[10;7].',
          'Common mistake: assuming every square matrix has an inverse. A zero determinant means it does not.',
          'When sensor equations become linearly dependent, the associated matrix can lose rank, which later connects to observability.',
          [q('What does det(A)=0 imply?','A is singular and has no ordinary inverse.'),q('Why are determinants used with eigenvalues?','Eigenvalues satisfy det(λI-A)=0.'),q('Is explicit inversion always the best numerical method?','No. Solving linear systems directly is usually more numerically stable.')],
          'MATLAB: A=[2 1;1 2]; det(A); inv(A); A\\[10;7]',
          quiz('What does det(A)=0 mean?',['A is singular','A is identity','A is stable','A is diagonal'],0),
          'determinant'),
        L('Eigenvalues & Eigenvectors',
          'Eigenvalues are among the most important ideas in modern control. They describe the natural modes of a state-space system.',
          'An eigenvector v keeps its direction under multiplication by A, while being scaled by eigenvalue λ: Av=λv. Eigenvalues satisfy det(λI-A)=0.',
          'Av=λv,   det(λI-A)=0.  For ẋ=Ax, eigenvalues of A determine natural response modes.',
          'For A=[[0,1],[-3,-4]], det(λI-A)=λ²+4λ+3=(λ+1)(λ+3), so λ=-1,-3.',
          'Find the eigenvalues of [[0,1],[-2,-3]]. Then explain what their signs suggest about stability.',
          'Common mistake: writing det(A-λI) inconsistently and then losing signs. Either convention works if used consistently because both yield the same roots up to a constant factor.',
          'In a motor, vehicle, or aircraft model, eigenvalues summarize how internal motion naturally decays, oscillates, or diverges.',
          [q('What is an eigenvalue physically in control?','A number associated with a natural system mode; its location influences decay, growth, and oscillation.'),q('How are state-space eigenvalues related to poles?','For a minimal LTI realization, the eigenvalues of A correspond to system poles.'),q('What does a positive real eigenvalue imply?','An unstable growing mode.')],
          'MATLAB: A=[0 1;-3 -4]; [V,D]=eig(A)',
          quiz('Which equation defines eigenvalues?',['det(λI-A)=0','A+B=I','Cx=D','AB=BA'],0),
          'eigen'),
        L('Derivatives, Integrals & Physical Meaning',
          'A derivative measures how fast something changes. An integral accumulates change. Control systems are full of position, velocity, acceleration, charge, current, and stored energy.',
          'If x is position, ẋ is velocity and ẍ is acceleration. Integration reverses differentiation under appropriate conditions.',
          'v=dx/dt, a=d²x/dt², x(t)=x(0)+∫v(t)dt.',
          'If x(t)=3t², then v(t)=6t and a(t)=6. If velocity is constant 2 m/s, position grows linearly.',
          'Differentiate 5e⁻²ᵗ and sin(4t). Integrate 3t² from 0 to T.',
          'Common mistake: forgetting the chain rule, e.g. d/dt sin(4t)=4cos(4t), not cos(4t).',
          'Cruise control regulates vehicle speed, while suspension control often cares about position, velocity, and acceleration simultaneously.',
          [q('What does a derivative represent?','Instantaneous rate of change.'),q('What does integration represent?','Accumulation over time.'),q('Why does angle often create an integrator from angular velocity?','Because angle is the time integral of angular velocity.')],
          'MATLAB symbolic example: syms t; diff(exp(-2*t),t)',
          quiz('If x(t)=t³, what is ẋ(t)?',['3t²','t²','3t','t⁴'],0),
          'derivative'),
        L('Differential Equations for Dynamic Systems',
          'Physical systems are usually described first by differential equations. Control modeling is the art of turning those equations into forms we can analyze and design around.',
          'A linear constant-coefficient ODE such as m ẍ+b ẋ+kx=f(t) describes a mass-spring-damper. Order equals the highest derivative order.',
          'm ẍ+b ẋ+kx=f(t).  A second-order system needs two independent initial conditions.',
          'With m=1,b=4,k=3: ẍ+4ẋ+3x=f(t). The homogeneous characteristic roots are -1 and -3.',
          'Write the differential equation for a rotational inertia J with viscous friction b and applied torque τ(t).',
          'Common mistake: mixing force directions or signs. Draw a free-body diagram before writing Newton’s law.',
          'Suspensions, robotic joints, RLC circuits, and motors can all be represented by differential equations before being transformed to transfer-function or state-space models.',
          [q('What determines ODE order?','The highest derivative present.'),q('Why are initial conditions important?','They describe stored initial energy/state and affect the total response.'),q('What makes an ODE linear?','The dependent variables and their derivatives appear linearly, without products or nonlinear functions of them.')],
          'MATLAB: use ode45 for nonlinear or general ODE simulation; transfer-function tools work after LTI modeling.',
          quiz('What is the order of x⃛+2ẋ+x=u?',['3','2','1','4'],0),
          'massspring'),
        L('Laplace Transform & Partial Fractions',
          'The Laplace transform turns differential equations into algebraic equations in s. This is why classical control can work so efficiently with transfer functions.',
          'Under zero initial conditions, L{ẋ}=sX(s), L{ẍ}=s²X(s). Common transforms include 1↔1/s and e⁻ᵃᵗ↔1/(s+a). Partial fractions help invert rational functions.',
          'm s²X+b sX+kX=F ⇒ X/F=1/(ms²+bs+k).',
          'For ẍ+4ẋ+3x=f, X/F=1/(s²+4s+3)=1/[(s+1)(s+3)].',
          'Find the transfer function of 2ÿ+5ẏ+3y=u under zero initial conditions. Then factor the denominator.',
          'Common mistake: using derivative transform formulas for zero initial conditions when the problem specifies nonzero initial conditions.',
          'Laplace-domain models are widely used for filters, motor control, process control, and classical feedback design.',
          [q('Why is Laplace useful?','It converts linear differential equations into algebraic equations in s.'),q('What assumption often defines a transfer function?','Zero initial conditions.'),q('What does 1/s represent in time domain?','A unit step.')],
          'MATLAB: tf([1],[1 4 3]); pole(ans); step(ans)',
          quiz('Under zero initial conditions, L{ẍ} equals?',['s²X(s)','sX(s)','X(s)/s','2sX(s)'],0),
          'laplace')
      ]
    },
    {
      id:1,title:'Control Systems Foundations',short:'Control Foundations',level:'Beginner',icon:'↺',
      description:'Understand feedback before equations become complicated: inputs, outputs, disturbances, open-loop vs closed-loop, stability, tracking, and physical intuition.',
      lessons:[
        L('What Is a Control System?',
          'A control system makes a physical process behave the way we want despite uncertainty and disturbance.',
          'Identify plant, actuator, sensor, controller, reference, output, and disturbance. Control engineering is about shaping behavior, not merely computing equations.',
          'Basic feedback error: e(t)=r(t)-y_m(t), where y_m is measured output.',
          'A thermostat compares desired temperature with measured temperature and switches or modulates heating.',
          'For cruise control, name the reference, plant, actuator, sensor, disturbance, and output.',
          'Common mistake: calling the plant the controller. The plant is the physical process being controlled.',
          'Cruise control must reject hills and wind while keeping speed near the driver’s command.',
          [q('What is the reference?','The desired target value.'),q('What is a disturbance?','An unwanted external influence on the plant.'),q('Why use feedback?','To correct deviations using measured output information.')],
          'MATLAB is not needed yet. Sketch a feedback loop first.',
          quiz('In cruise control, vehicle speed is usually the?',['Output','Controller','Disturbance','Actuator'],0),
          'feedback'),
        L('Open-Loop vs Closed-Loop Feedback',
          'Open-loop control acts without checking the result. Closed-loop control measures the result and corrects itself.',
          'Open-loop systems are simple but sensitive to uncertainty. Closed-loop systems can reject disturbances and reduce sensitivity, but poor feedback design can destabilize a system.',
          'For negative feedback: T(s)=G(s)/(1+G(s)H(s)).',
          'A timed toaster is mostly open loop. A temperature-controlled oven is closed loop.',
          'List two advantages and two disadvantages of feedback.',
          'Common mistake: assuming feedback always improves a system. Excessive gain, delay, or wrong sign can create oscillation or instability.',
          'Aircraft attitude control continuously measures orientation and corrects control surfaces.',
          [q('What is the main difference?','Closed loop uses measured output feedback; open loop does not.'),q('Can feedback cause instability?','Yes, if the loop is poorly designed.'),q('Why does negative feedback help reject disturbances?','It reacts to output deviations and drives the error toward zero.')],
          'MATLAB: feedback(G,H) forms a closed-loop model.',
          quiz('Which system is clearly closed-loop?',['Thermostat-controlled heater','Simple timer','Fixed-voltage lamp','Manual switch'],0),
          'feedback'),
        L('Signals, Inputs, Outputs & Disturbances',
          'Control diagrams become easier when every arrow has a physical meaning.',
          'Inputs may be commands or disturbances. Outputs are measured performance variables. Internal states can matter even when they are not directly measured.',
          'Common test inputs: impulse δ(t), step 1(t), ramp t, sinusoid sin(ωt).',
          'A step command models a sudden target change; a ramp models a steadily increasing target.',
          'For a water-level system, identify a step command, a disturbance, and an output.',
          'Common mistake: confusing the plant input with the reference. A controller may transform reference error into a very different actuator signal.',
          'Process plants often face inflow disturbances while regulating temperature, pressure, or level.',
          [q('What is a step input useful for?','Testing transient and steady-state response to a sudden command change.'),q('What is a ramp input useful for?','Testing tracking of a steadily changing command.'),q('Can a disturbance enter inside the plant?','Yes. Disturbances can enter at different points in a system.')],
          'MATLAB: step(sys), impulse(sys), lsim(sys,u,t).',
          quiz('A steadily increasing command is best modeled by a?',['Ramp','Impulse','Constant zero','Noise only'],0),
          'signals'),
        L('Stability, Performance & Robustness',
          'A system can track well only if it remains well-behaved. Stability is the first requirement, but useful control also needs acceptable speed, accuracy, and robustness.',
          'Performance includes rise time, overshoot, settling time, steady-state error, disturbance rejection, and control effort. Robustness means maintaining acceptable behavior despite uncertainty.',
          'Stable continuous LTI poles have negative real parts. Performance specifications later constrain pole locations.',
          'Two controllers can both be stable, but one may settle in 1 second while another takes 20 seconds.',
          'Compare two hypothetical designs: one with 50% overshoot and 0.5 s settling, another with 5% overshoot and 3 s settling. Which is better depends on the application.',
          'Common mistake: equating stability with good performance. A very slow stable system may still be unacceptable.',
          'Medical infusion, aircraft, and autonomous vehicles place very different priorities on speed, overshoot, and robustness.',
          [q('What is robustness?','Ability to maintain acceptable behavior under uncertainty or variation.'),q('Is every stable system satisfactory?','No.'),q('Name two performance measures.','Examples: rise time, overshoot, settling time, steady-state error.')],
          'MATLAB: stepinfo(sys) reports common time-response metrics.',
          quiz('Which is a performance metric?',['Settling time','File size','Matrix color','Sensor brand'],0),
          'performance'),
        L('Continuous-Time vs Discrete-Time Systems',
          'Physical plants evolve continuously, while digital controllers compute at discrete sampling instants.',
          'Continuous-time models use differential equations. Discrete-time models use difference equations. Sampling rate must be fast enough to capture relevant dynamics.',
          'Continuous: ẋ=Ax+Bu. Discrete: x[k+1]=A_d x[k]+B_d u[k].',
          'A motor rotates continuously, but a microcontroller may update its control voltage every 1 ms.',
          'Explain what could go wrong if a fast mechanical system is sampled only once per second.',
          'Common mistake: assuming discretization is simply replacing t with k. Sampling changes the model mathematically.',
          'Nearly all embedded control systems use digital computation to control continuous physical plants.',
          [q('What is sampling?','Measuring/computing a continuous process at discrete time instants.'),q('What does k index?','Discrete-time sample number.'),q('Why does sample rate matter?','Too-slow sampling can miss dynamics and degrade or destabilize control.')],
          'MATLAB: c2d(sys,Ts) converts a continuous LTI model to a discrete model using a chosen method.',
          quiz('Which equation is discrete-time?',['x[k+1]=Ax[k]+Bu[k]','ẋ=Ax+Bu','y=mx+b only','F=ma'],0),
          'sampling'),
        L('How to Read a Block Diagram',
          'Block diagrams are a visual language for signal flow. Read them from left to right while tracking summing points, blocks, branches, and feedback paths.',
          'Blocks represent transfer relationships. Summing junctions add or subtract signals. Pickoff points duplicate a signal without changing it.',
          'Series: G₁G₂. Parallel: G₁+G₂. Negative feedback: G/(1+GH).',
          'Two blocks 2/(s+1) and 1/(s+3) in series give 2/[(s+1)(s+3)].',
          'Reduce a series pair, then place it in unity negative feedback.',
          'Common mistake: using 1-GH in the denominator for negative feedback. The standard negative-feedback denominator is 1+GH.',
          'Industrial control diagrams combine sensors, filters, controllers, actuators, and plant dynamics.',
          [q('What does a summing junction do?','Adds or subtracts input signals.'),q('How do series blocks combine?','Multiply their transfer functions.'),q('How do parallel blocks combine?','Add or subtract their transfer functions depending on signs.')],
          'MATLAB: series(G1,G2), parallel(G1,G2), feedback(G,H).',
          quiz('For negative feedback, the closed-loop denominator is usually?',['1+GH','1-GH','G+H','GH only'],0),
          'block')
      ]
    },
    {
      id:2,title:'Mathematical Modeling',short:'Modeling',level:'Beginner',icon:'⚙',
      description:'Build dynamic models from physics: mechanical systems, RLC circuits, DC motors, nonlinear models, linearization, transfer functions, and block diagrams.',
      lessons:[
        L('Mass-Spring-Damper Modeling',
          'A mass stores kinetic energy, a spring stores potential energy, and a damper dissipates energy. This single example teaches the structure of many second-order systems.',
          'Apply Newton’s second law with consistent force directions. For displacement x and applied force f: m ẍ+b ẋ+kx=f.',
          'm ẍ+b ẋ+kx=f(t),  G(s)=X/F=1/(ms²+bs+k) under zero initial conditions.',
          'With m=1,b=4,k=3: G(s)=1/(s²+4s+3)=1/[(s+1)(s+3)].',
          'Derive the model for m=2,b=6,k=8 and identify order and poles.',
          'Common mistake: writing the damping force as +b ẋ in the force balance without first defining direction. Derive signs from the free-body diagram.',
          'Vehicle suspension, vibration isolation, and precision positioning use closely related mass-spring-damper models.',
          [q('What physical element dissipates energy?','The damper.'),q('What is the system order?','Second order.'),q('What do m, b, and k represent?','Mass, damping coefficient, and spring stiffness.')],
          "MATLAB: m=1;b=4;k=3; G=tf(1,[m b k]); pole(G); step(G)",
          quiz('For m ẍ+b ẋ+kx=f, what is X/F?',['1/(ms²+bs+k)','ms²+bs+k','s/(m+b+k)','k/(s+m)'],0),
          'massspring'),
        L('RLC Circuit Modeling',
          'Electrical and mechanical systems can have the same mathematical structure even though their physical variables differ.',
          'Use KVL and element laws. For series RLC with capacitor output, the denominator is LC s²+RC s+1.',
          'G(s)=V_C/V_in = 1/(LCs²+RCs+1).',
          'With L=1,R=4,C=1/3, denominator=(1/3)s²+(4/3)s+1, proportional to s²+4s+3.',
          'Derive the transfer function for L=2, R=3, C=0.5.',
          'Common mistake: forgetting that capacitor voltage relates to current through i=C dv_C/dt.',
          'RLC circuits model filters, power electronics, and resonant electrical networks.',
          [q('What stores magnetic energy?','The inductor.'),q('What stores electric-field energy?','The capacitor.'),q('What dissipates energy?','The resistor.')],
          'MATLAB: L=1;R=4;C=1/3; G=tf(1,[L*C R*C 1]); step(G)',
          quiz('Which mechanical parameter is analogous to resistance in the common force-voltage analogy?',['Damping b','Mass m','Stiffness k','Position x'],0),
          'rlc'),
        L('DC Motor Modeling',
          'A DC motor links electrical dynamics to mechanical rotation. It is an excellent bridge between circuits and motion.',
          'Armature voltage drives current; current produces torque; rotation creates back EMF. Depending on assumptions, inductance may be retained or neglected.',
          'Va=Ra ia+La dia/dt+Keω;  J dω/dt+bω=Kt ia.',
          'If La is neglected, substitute ia=(Jω̇+bω)/Kt into the armature equation to obtain a first-order speed model. Position adds an integrator because θ̇=ω.',
          'Derive Ω(s)/Va(s) with La neglected. Then derive Θ(s)/Va(s).',
          'Common mistake: forgetting the back-EMF term Keω, which changes the effective denominator.',
          'DC motor models appear in robotics, conveyors, drives, automotive actuators, and laboratory control rigs.',
          [q('What produces motor torque?','Armature current through the torque constant Kt.'),q('Why does position add a pole at the origin?','Because θ is the integral of angular velocity.'),q('What is back EMF?','A voltage proportional to motor speed that opposes the applied armature voltage.')],
          'MATLAB: construct the derived transfer function with tf() and compare speed and position responses.',
          quiz('What relation connects angle and angular speed?',['θ̇=ω','θ=ω̇','ω=θ̈','θω=1'],0),
          'motor'),
        L('Nonlinear Models & Equilibrium Points',
          'Many real systems are nonlinear. Modern control often begins by identifying an operating point and building a local linear model around it.',
          'For ẋ=f(x,u), an equilibrium satisfies 0=f(x_e,u_e) for constant input u_e.',
          'Example: ẋ=-x²+u. For u_e=1, equilibria satisfy x_e²=1, so x_e=±1.',
          'At each equilibrium, local behavior can differ even though it comes from the same nonlinear equation.',
          'Find equilibria of ẋ=x-x³+u for u=0.',
          'Common mistake: setting x=0 automatically instead of solving f(x_e,u_e)=0.',
          'Aircraft trim points, robot balance positions, chemical reactor operating points, and vehicle speeds are equilibrium concepts.',
          [q('What defines an equilibrium?','The state derivative is zero for the chosen constant input.'),q('Can one nonlinear system have multiple equilibria?','Yes.'),q('Why choose an operating point?','To analyze behavior around a specific condition of interest.')],
          'MATLAB: solve symbolic equilibrium equations or use numerical root-finding.',
          quiz('For ẋ=-x²+4, equilibria are?',['x=±2','x=4 only','x=0 only','x=±4'],0),
          'nonlinear'),
        L('Linearization with Taylor Expansion',
          'Linearization replaces a nonlinear system by a nearby linear approximation. It is powerful, but only locally valid.',
          'For ẋ=f(x,u), define perturbations δx=x-x_e, δu=u-u_e. Then δẋ≈Aδx+Bδu, where A=∂f/∂x and B=∂f/∂u at the operating point.',
          'A=∂f/∂x|e,  B=∂f/∂u|e.',
          'For f=-x²+u, A=-2x_e and B=1. Around x_e=+1, A=-2; around -1, A=+2.',
          'Linearize ẋ=sin(x)+u around x_e=0,u_e=0.',
          'Common mistake: computing derivatives but forgetting to evaluate them at the chosen equilibrium.',
          'Flight control, engine control, and process control frequently use linearized models around trim or operating conditions.',
          [q('Why is linearization local?','Higher-order nonlinear terms are neglected, so accuracy is best near the operating point.'),q('What is A in a nonlinear state model?','The Jacobian of f with respect to states at the operating point.'),q('Can different equilibria have different local stability?','Yes.')],
          'MATLAB/Simulink can linearize models around operating points using linearization tools.',
          quiz('For f(x,u)=-x²+u, what is ∂f/∂x?',['-2x','-x','1','2u'],0),
          'linearize'),
        L('Block Diagram Reduction & Closed-Loop Models',
          'A block diagram is an algebraic representation of cause and effect. Reduction turns a complex diagram into one equivalent transfer function.',
          'Combine series, parallel, and feedback structures systematically. Do not skip sign conventions.',
          'Series G=G₁G₂; negative feedback T=G/(1+GH).',
          'If G₁=2/(s+1), G₂=1/(s+3), H=1, then G=2/(s²+4s+3) and T=2/(s²+4s+5).',
          'Repeat the reduction with H=0.5.',
          'Common mistake: multiplying H into the forward numerator when the diagram only places H in the feedback path.',
          'Block reduction is used to reason about cascaded actuator, plant, sensor, and filter dynamics.',
          [q('What is unity feedback?','H(s)=1.'),q('What determines closed-loop poles?','Roots of the closed-loop denominator.'),q('Does feedback change poles?','Generally yes.')],
          'MATLAB: G=series(G1,G2); T=feedback(G,H); pole(T)',
          quiz('If G=2/(s²+4s+3) and H=1, closed-loop T is?',['2/(s²+4s+5)','2/(s²+4s+3)','1/(s²+4s+5)','2/(s²+2s+3)'],0),
          'block')
      ]
    },
    {
      id:3,title:'Classical Control Refresher',short:'Classical Control',level:'Intermediate',icon:'∿',
      description:'Recover the Control Systems I ideas that Modern Control assumes: poles/zeros, time response, steady-state error, Routh, root locus, frequency response, and PID.',
      lessons:[
        L('Poles, Zeros & System Type',
          'Poles describe natural dynamics; zeros reshape how inputs excite those dynamics. System type counts open-loop integrators relevant to steady-state tracking.',
          'Poles are denominator roots, zeros numerator roots after cancellation considerations. Type is the number of poles at the origin in the open-loop transfer function for standard unity-feedback error analysis.',
          'G(s)=20(s+2)/[s(s+1)(s+5)] has one pole at zero, so it is Type 1.',
          'Type 1 systems can track a step with zero steady-state error under usual stability conditions and have finite ramp error.',
          'Determine type, poles, and zeros of K/[s²(s+4)].',
          'Common mistake: counting all poles instead of only poles at the origin when determining system type.',
          'Position control often uses integral action to eliminate constant position error.',
          [q('What defines system type?','Number of open-loop poles at the origin for the relevant loop transfer function.'),q('What is a zero?','A root of the transfer-function numerator.'),q('Why are poles important?','They govern natural response and stability.')],
          'MATLAB: pole(G), zero(G), pzmap(G).',
          quiz('G=K/[s²(s+4)] is which type?',['Type 2','Type 1','Type 0','Type 4'],0),
          'splane'),
        L('Steady-State Error & Error Constants',
          'Steady-state error tells you what remains after transients die out. It is the long-term tracking accuracy of a stable feedback system.',
          'For unity feedback, common error constants are Kp=lim G(s), Kv=lim sG(s), Ka=lim s²G(s) as s→0. Applicable finite constants depend on system type.',
          'Type 0: step error 1/(1+Kp). Type 1: step error 0, ramp error 1/Kv. Type 2: step/ramp error 0, parabolic error 1/Ka.',
          'For G=20(s+2)/[s(s+1)(s+5)], Kv=lim sG=20·2/(1·5)=8, so unit-ramp e_ss=1/8.',
          'Compute Kp, Kv, Ka where applicable and step/ramp/parabolic error for G=K/[s²(s+4)].',
          'Common mistake: applying 1/(1+Kp) to a Type 1 ramp input. Match the input class to the correct constant.',
          'Tracking accuracy matters in servo positioning, robotics, antenna pointing, and speed regulation.',
          [q('What does Kv measure?','Velocity/ramp tracking error constant.'),q('What theorem often computes steady-state error?','Final value theorem, when its conditions are satisfied.'),q('Does higher gain usually reduce steady-state error?','Often yes, but it can hurt robustness or stability.')],
          'MATLAB: simulate step() and lsim() and compare final error to the hand calculation.',
          quiz('For a stable Type 1 unity-feedback system, unit-step steady-state error is usually?',['0','1','∞','Kv'],0),
          'error'),
        L('Second-Order Transient Response',
          'A huge amount of control intuition comes from one standard second-order model.',
          'Standard form uses natural frequency ωn and damping ratio ζ. For 0<ζ<1, poles are -ζωn±jωn√(1-ζ²).',
          'T_p=π/ωd, %OS=100e^{-ζπ/√(1-ζ²)}, T_s≈4/(ζωn) for 2% criterion, ωd=ωn√(1-ζ²).',
          'With ζ=0.5, ωn=4: ωd≈3.464, poles=-2±j3.464, T_s≈2 s.',
          'Compute peak time, overshoot, settling time, and poles for ζ=0.7,ωn=5.',
          'Common mistake: using ωn where the peak-time formula requires ωd.',
          'Suspension comfort, motor positioning, and aircraft attitude response are often judged by overshoot and settling time.',
          [q('What does increasing ζ generally do?','Reduces overshoot and oscillation, while possibly slowing rise.'),q('What does ωn mainly scale?','Speed of the response.'),q('Where are underdamped poles?','A complex-conjugate pair in the left half-plane for stable systems.')],
          'MATLAB: stepinfo(sys) and damp(sys).',
          quiz('The 2% settling-time approximation is?',['4/(ζωn)','π/ωn','ζ/ωn','1/ζ²'],0),
          'secondorder'),
        L('Dominant Poles & the Effect of Zeros',
          'Higher-order systems often behave approximately like a dominant second-order pair when other poles are much faster.',
          'A common rule of thumb is that neglected poles should be several times farther left than the dominant real part. Zeros near dominant poles can strongly change transient shape.',
          'A third pole at -p is less influential when p is much larger than the dominant decay rate.',
          'Compare dominant poles -2±j3 with a third pole at -8 versus -40. The -40 pole is much more safely negligible.',
          'Explain how a left-half-plane zero at -2 versus -10 changes a nominal second-order step response.',
          'Common mistake: assuming a distant pole is irrelevant without checking relative time scales.',
          'Real actuators and sensors add extra poles and zeros that can invalidate simple second-order approximations.',
          [q('What makes a pole dominant?','It decays more slowly and therefore shapes the visible transient more strongly.'),q('Can zeros affect overshoot?','Yes, especially zeros near dominant poles.'),q('Why use approximations?','To gain insight and simplify design while preserving the main dynamics.')],
          'MATLAB: compare step responses while moving an added pole or zero.',
          quiz('Which extra pole is more safely negligible relative to dominant real part -2?',['-40','-3','-2.5','-1'],0),
          'dominant'),
        L('Routh-Hurwitz Stability Refresher',
          'Routh-Hurwitz lets you count right-half-plane roots without explicitly solving a high-order polynomial.',
          'Build the Routh array from characteristic polynomial coefficients. Sign changes in the first column equal the number of right-half-plane roots.',
          'For low orders, direct reasoning may be faster, but Routh becomes valuable for parameter ranges.',
          'For s³+2s²+3s+K, build the Routh array and derive a K range for stability.',
          'Practice the full array and interpret zero-row special cases separately.',
          'Common mistake: losing coefficient order or skipping zeros in the polynomial.',
          'Gain-range stability checks appear in classical controller tuning and parameter robustness studies.',
          [q('What do first-column sign changes represent?','Number of right-half-plane roots.'),q('Does Routh give exact root locations?','No, primarily stability/root-count information.'),q('What polynomial is used?','The closed-loop characteristic polynomial.')],
          'MATLAB can verify results with roots() or pole() after the hand analysis.',
          quiz('Routh sign changes count roots in which region?',['Right half-plane','Left half-plane only','Imaginary axis only','z-plane unit circle'],0),
          'routh'),
        L('Root Locus Refresher',
          'Root locus shows how closed-loop poles move as gain changes. It turns a parameter sweep into a geometric picture.',
          'Root locus starts at open-loop poles and ends at zeros (including zeros at infinity). Real-axis rules, asymptotes, breakaway points, and angle conditions guide the sketch.',
          'Characteristic equation: 1+KG(s)H(s)=0.',
          'For G=1/[s(s+2)], poles move from 0 and -2 and eventually form a complex pair as K increases.',
          'Sketch the root locus of K/[s(s+1)(s+4)] and identify likely stability behavior.',
          'Common mistake: drawing locus branches that do not start at open-loop poles.',
          'Root locus helps tune gain for desired damping and speed while observing stability margins.',
          [q('Where do root-locus branches start?','At open-loop poles.'),q('What parameter usually varies?','Loop gain K.'),q('What equation defines closed-loop poles?','1+KG(s)H(s)=0.')],
          'MATLAB: rlocus(G); sgrid(zeta,wn).',
          quiz('Root locus shows movement of?',['Closed-loop poles','Open-loop zeros only','Inputs','Sensor noise'],0),
          'rootlocus'),
        L('Bode & Frequency Response Refresher',
          'Frequency response tells how a system responds to sinusoids of different frequencies. It is central to robustness and disturbance/noise reasoning.',
          'Bode plots show magnitude and phase versus logarithmic frequency. Gain margin and phase margin estimate distance from instability.',
          'Each pole/zero contributes characteristic slope and phase changes.',
          'A low-pass plant attenuates high-frequency noise but may add phase lag near crossover.',
          'Sketch asymptotic magnitude for 10/[s(1+s/10)].',
          'Common mistake: adding dB slopes incorrectly or forgetting the integrator contributes -20 dB/dec and -90° phase.',
          'Servo loops, power electronics, audio, aerospace, and process control all use frequency-domain robustness analysis.',
          [q('What does phase margin indicate?','A measure of robustness relative to phase-induced instability.'),q('Why use log frequency?','It shows wide frequency ranges compactly.'),q('What does an integrator contribute to magnitude slope?','-20 dB/decade.')],
          'MATLAB: bode(G); margin(G).',
          quiz('An integrator contributes what asymptotic magnitude slope?',['-20 dB/dec','+20 dB/dec','0 dB/dec','-40 dB/dec'],0),
          'bode'),
        L('PID Control Refresher',
          'PID combines proportional action, integral memory, and derivative prediction-like damping. It remains one of the most common industrial controllers.',
          'P reacts to present error, I accumulates past error, D reacts to error rate. Real implementations filter derivative action and manage saturation.',
          'C(s)=Kp+Ki/s+Kd s (ideal form).',
          'Increasing Ki can remove steady-state error but may increase overshoot. Increasing Kd can add damping but amplify noise.',
          'For a slow Type 0 plant, describe which PID term directly adds an integrator and why that changes tracking.',
          'Common mistake: using unfiltered derivative on noisy measurements.',
          'Temperature, speed, flow, pressure, and motion loops commonly use PI/PID control.',
          [q('Which term removes constant steady-state error most directly?','Integral action.'),q('Which term is sensitive to high-frequency noise?','Derivative action.'),q('What does proportional action do?','Produces control proportional to current error.')],
          'MATLAB: pid(Kp,Ki,Kd); pidtune(G,"PID").',
          quiz('Which PID term contains 1/s?',['Integral','Proportional','Derivative','Feedforward'],0),
          'pid')
      ]
    },
    {
      id:4,title:'State-Space Fundamentals',short:'State Space',level:'Intermediate',icon:'A',
      description:'Make the transition from transfer functions to the language of modern control: states, A/B/C/D matrices, realizations, conversions, and physical meaning.',
      lessons:[
        L('Why State Space?',
          'Transfer functions describe input-output behavior. State space also exposes what is happening inside the system.',
          'State-space form supports MIMO systems, nonzero initial conditions, modern design methods, and direct use of linear algebra.',
          'ẋ=Ax+Bu,  y=Cx+Du.',
          'A mass-spring-damper can use x₁=position and x₂=velocity. Then ẋ₁=x₂ and ẋ₂=-(k/m)x₁-(b/m)x₂+(1/m)u.',
          'Explain why a two-energy-storage-element system often needs two states.',
          'Common mistake: choosing dependent variables as separate states.',
          'Aircraft, robots, vehicles, power systems, and chemical processes are naturally multivariable and benefit from state-space models.',
          [q('What is a state?','A minimal internal variable needed, together with input, to predict future behavior.'),q('What does A describe?','Internal state-to-state dynamics.'),q('What does B describe?','How inputs affect state derivatives.')],
          'MATLAB: sys=ss(A,B,C,D).',
          quiz('Which matrix maps the state to the output?',['C','A','B','I'],0),
          'statespace',
          'https://www.mathworks.com/videos/introduction-to-state-space-equations-1547129824178.html'),
        L('Choosing State Variables',
          'Good state choices correspond to stored energy or physically meaningful quantities and make equations easy to write.',
          'For an nth-order system, a minimal realization usually has n independent states. Common choices include position/velocity, capacitor voltage/inductor current, or successive derivatives.',
          'If x₁=x and x₂=ẋ, then ẋ₁=x₂.',
          'For a series RLC circuit, choose capacitor voltage and inductor current as states.',
          'Choose states for a rotational inertia-spring-damper system and justify them.',
          'Common mistake: choosing the input or output automatically as a state without checking whether it stores independent system memory.',
          'Energy-storage thinking works across mechanical, electrical, fluid, and thermal systems.',
          [q('Why are capacitor voltage and inductor current natural states?','They correspond to stored electrical energy.'),q('Can output equal a state?','Yes, but it does not have to.'),q('What does state independence mean?','No chosen state is completely determined by the others at the same instant.')],
          'MATLAB does not choose physical states automatically when converting arbitrary transfer functions; realizations can differ.',
          quiz('For a mass-spring-damper, a natural state pair is?',['Position and velocity','Force and mass','Spring and damper','Time and gain'],0),
          'energy'),
        L('Building A, B, C, D from Equations',
          'Once first-order equations are written, the matrices are mostly bookkeeping.',
          'Place coefficients of states into A, coefficients of inputs into B, output-state coefficients into C, and direct input-to-output feedthrough into D.',
          'For ẋ₁=x₂; ẋ₂=-3x₁-4x₂+u: A=[[0,1],[-3,-4]], B=[[0],[1]]. If y=x₁, C=[1,0],D=0.',
          'Check each row against one differential equation.',
          'Convert ẍ+5ẋ+6x=2u to state space using x₁=x,x₂=ẋ.',
          'Common mistake: placing coefficients into the wrong A row or swapping state order.',
          'This matrix assembly is used whenever physics gives coupled first-order equations.',
          [q('What is D?','Direct feedthrough from input to output.'),q('What determines A dimensions?','Number of states: n×n.'),q('What is B size for n states and m inputs?','n×m.')],
          'MATLAB: A=[0 1;-3 -4]; B=[0;1]; C=[1 0]; D=0; ss(A,B,C,D)',
          quiz('If there are 3 states and 2 inputs, B is?',['3×2','2×3','3×3','2×2'],0),
          'abcd'),
        L('Transfer Function to State Space',
          'A transfer function can be realized by many different state-coordinate choices. Canonical forms provide systematic constructions.',
          'Controllable canonical form places denominator coefficients into a companion matrix. Different realizations can have different A,B,C matrices but the same input-output transfer function.',
          'G(s)=C(sI-A)⁻¹B+D.',
          'For G=10/(s³+6s²+11s+6), a controllable companion realization can be built directly from denominator coefficients.',
          'Build a controllable canonical realization for 1/(s²+5s+6).',
          'Common mistake: assuming tf2ss() must return the same state variables as a hand-derived physical model.',
          'Software often changes coordinates internally while preserving the same transfer behavior.',
          [q('Can one transfer function have multiple state-space realizations?','Yes.'),q('What stays the same across equivalent realizations?','Input-output behavior and eigenvalues for minimal similar realizations.'),q('What is a canonical form?','A standardized state-space arrangement useful for analysis and construction.')],
          'MATLAB: [A,B,C,D]=tf2ss(num,den).',
          quiz('Equivalent minimal realizations can have different?',['State coordinates','Transfer function','Pole set','System order'],0),
          'canonical'),
        L('State Space to Transfer Function',
          'State-space and transfer-function descriptions are two views of the same LTI input-output dynamics when initial conditions are zero.',
          'Use G(s)=C(sI-A)⁻¹B+D.',
          'The denominator includes det(sI-A), though pole-zero cancellation can matter in nonminimal realizations.',
          'For A=[[0,1],[-2,-3]],B=[0;1],C=[1,0],D=0, compute (sI-A)⁻¹ and obtain G(s)=1/(s²+3s+2).',
          'Convert a 2×2 state model to transfer function by hand.',
          'Common mistake: forgetting D when direct feedthrough exists.',
          'Engineers move between representations depending on whether classical or modern design tools are more convenient.',
          [q('What matrix expression is inverted?','sI-A.'),q('What is added after C(sI-A)⁻¹B?','D.'),q('Do nonzero initial conditions appear in the transfer function?','Not in the standard transfer-function definition.')],
          'MATLAB: tf(ss(A,B,C,D)) or ss2tf().',
          quiz('State-space to transfer function uses?',['C(sI-A)⁻¹B+D','A+B+C+D','ABCD','det(A+B)'],0),
          'transfer'),
        L('Similarity Transformations',
          'Changing state coordinates does not change the physical input-output system. It changes only how the internal coordinates are described.',
          'For x=Tz, transformed matrices are A_z=T⁻¹AT, B_z=T⁻¹B, C_z=CT, D unchanged.',
          'A and T⁻¹AT have the same eigenvalues.',
          'A physical position-velocity model can be transformed to modal coordinates that decouple modes when diagonalization is possible.',
          'Verify with a simple invertible T that eigenvalues are preserved.',
          'Common mistake: using TAT⁻¹ instead of T⁻¹AT after choosing x=Tz. The formula depends on the coordinate convention.',
          'Modal coordinates can simplify vibration, aircraft, and structural control analysis.',
          [q('What is preserved by similarity?','Eigenvalues and input-output behavior when B and C are transformed consistently.'),q('Why transform coordinates?','To simplify structure or reveal modes.'),q('Must T be invertible?','Yes.')],
          'MATLAB: inv(T)*A*T or, preferably, T\\(A*T).',
          quiz('A similarity transform preserves?',['Eigenvalues','Every matrix entry','State variable names','Units automatically'],0),
          'similarity'),
        L('Continuous vs Discrete State Space',
          'Modern control applies to both differential and difference equations. Digital controllers require discrete-time thinking.',
          'Continuous: ẋ=Ax+Bu. Discrete: x[k+1]=Adx[k]+Bdu[k]. Exact zero-order-hold discretization depends on the matrix exponential.',
          'Ad=e^{ATs}; Bd=∫₀^{Ts}e^{Aτ}B dτ.',
          'A stable continuous mode e^{-2t} sampled every Ts becomes discrete eigenvalue e^{-2Ts}, inside the unit circle.',
          'For λ=-2 and Ts=0.1, calculate z=e^{-0.2}.',
          'Common mistake: applying left-half-plane stability directly to discrete eigenvalues. Discrete-time stability uses the unit circle.',
          'Microcontrollers, digital motor drives, drones, and embedded systems all implement discrete-time controllers.',
          [q('Where must stable discrete-time eigenvalues lie?','Inside the unit circle.'),q('What is Ad for continuous A under exact sampling?','e^{ATs}.'),q('What is Ts?','Sampling period.')],
          'MATLAB: sysd=c2d(sys,Ts,"zoh"); eig(sysd.A).',
          quiz('Stable discrete-time poles lie?',['Inside the unit circle','Only in left half-plane','Outside unit circle','On positive real axis'],0),
          'sampling')
      ]
    },
    {
      id:5,title:'State-Space Analysis',short:'State Analysis',level:'Intermediate',icon:'eᴬᵗ',
      description:'Solve state equations, understand the state-transition matrix, modes, realizations, matrix exponentials, and time response.',
      lessons:[
        L('Homogeneous State Equation & Matrix Exponential','For ẋ=Ax with no input, the matrix exponential plays the role of e^{at} from a scalar first-order equation.','The solution is x(t)=e^{At}x(0). The matrix e^{At} is the state-transition matrix for LTI systems.','Φ(t)=e^{At}=I+At+A²t²/2!+…','If A is diagonal, e^{At} is obtained by exponentiating each diagonal element.','Compute e^{At} for A=diag(-1,-3).','Common mistake: exponentiating each entry of a general matrix. Matrix exponential is not elementwise exponential.','Natural modes of multi-axis vehicles and structures evolve through the state-transition matrix.',[q('What is Φ(t) for LTI systems?','e^{At}.'),q('What does it propagate?','The initial state.'),q('Can e^{At} be computed from eigen-decomposition?','Yes, when A is diagonalizable and by other methods generally.')],'MATLAB: expm(A*t), not exp(A*t).',quiz('Which MATLAB function computes matrix exponential?',['expm','exp','pow','matrixexp only'],0),'matrixexp'),
        L('Forced State Response','Inputs add a convolution-like term to the state response.','For LTI systems, x(t)=e^{At}x(0)+∫₀ᵗe^{A(t-τ)}Bu(τ)dτ.','x(t)=Φ(t)x0+∫Φ(t-τ)Bu(τ)dτ.','A constant input drives both transient and steady components.','Write the full solution formula and identify natural vs forced response.','Common mistake: dropping the initial-condition term even when x(0)≠0.','Startup conditions matter in spacecraft attitude, motor current, and energy-storage systems.',[q('What is natural response?','Response due to initial conditions.'),q('What is forced response?','Response due to input.'),q('What kernel appears in the integral?','e^{A(t-τ)}B.')],'MATLAB: initial(sys,x0), lsim(sys,u,t,x0).',quiz('Which term represents initial-condition response?',['e^{At}x(0)','Du only','C only','B⁻¹u'],0),'forced'),
        L('Modes, Eigenvectors & Modal Coordinates','A state response can be understood as a combination of modes. Eigenvectors describe mode directions; eigenvalues describe their time evolution.','If A=VΛV⁻¹, then e^{At}=Ve^{Λt}V⁻¹.','Mode i evolves like e^{λ_i t}.','For λ=-1 and -3, the -1 mode decays more slowly and often dominates later response.','For a two-mode system, identify which mode dominates after a long time.','Common mistake: assuming the largest magnitude eigenvalue dominates. In continuous stable systems, the eigenvalue closest to the imaginary axis usually decays slowest.','Flexible structures and aircraft have multiple modes with different damping and frequencies.',[q('What is a mode?','A characteristic natural response associated with an eigenvalue/eigenvector.'),q('Which stable mode decays slowest?','Usually the one with real part closest to zero.'),q('What are modal coordinates?','Coordinates aligned with system modes when transformation is possible.')],'MATLAB: [V,D]=eig(A); inspect D and V.',quiz('Between poles -1 and -5, which mode decays slower?',['-1','-5','Both same','Cannot say'],0),'modes'),
        L('Jordan Form & Repeated Eigenvalues','Not every matrix has enough independent eigenvectors to diagonalize. Jordan form handles defective cases.','Jordan blocks introduce polynomial factors multiplying exponentials, such as t e^{λt}.','For a 2×2 Jordan block J=[[λ,1],[0,λ]], e^{Jt}=e^{λt}[[1,t],[0,1]].','Repeated eigenvalues can be either diagonalizable or defective depending on eigenvectors.','Determine whether [[-1,1],[0,-1]] is diagonalizable.','Common mistake: assuming repeated eigenvalues automatically mean non-diagonalizable.','Jordan structure matters in theoretical analysis and understanding repeated modes.',[q('What is a defective matrix?','One lacking enough independent eigenvectors for diagonalization.'),q('What extra factor can Jordan blocks produce?','Polynomial-in-time factors such as t e^{λt}.'),q('Is Jordan form numerically ideal?','Usually not; it is mainly theoretical because it can be sensitive numerically.')],'MATLAB: jordan() exists in Symbolic Math Toolbox; numerical Schur form is often preferred.',quiz('A Jordan block with repeated λ can produce terms like?',['t e^{λt}','sin(t) only','1/t','No time dependence'],0),'jordan'),
        L('State Response vs Transfer Response','Transfer functions hide initial conditions, while state-space simulation can include them directly.','Two systems with the same transfer function can show different total responses if initialized differently.','y(t)=Cx(t)+Du(t).','A stable system with nonzero initial state may respond even when u=0.','Simulate zero-input response for x0=[1;0].','Common mistake: expecting step() to represent arbitrary nonzero initial conditions.','Stored mechanical/electrical energy can create motion even before a command input is applied.',[q('What does initial() simulate?','Response due to initial state with zero external input.'),q('Does a standard transfer function encode x0?','No.'),q('How is output computed from state?','y=Cx+Du.')],'MATLAB: initial(sys,x0); lsim(sys,u,t,x0).',quiz('Which command is suited to zero-input nonzero-initial-state response?',['initial','step only','margin','rlocus'],0),'initial'),
        L('Realizations & Minimality','A realization may contain internal states that do not affect input-output behavior. Minimal realizations remove unreachable or unobservable modes.','A realization is minimal if it is both controllable and observable. Pole-zero cancellations can signal hidden nonminimal dynamics.','Minimal order equals the McMillan degree for a rational transfer function.','A state model can contain an isolated stable state not connected to B or C; it will not appear in the transfer function.','Construct an example with one hidden state and compare state eigenvalues with transfer poles.','Common mistake: assuming every A eigenvalue must appear as a transfer pole even in nonminimal models.','Model reduction and system identification rely on distinguishing meaningful dynamics from redundant internal states.',[q('When is a realization minimal?','When it is controllable and observable.'),q('Can A contain hidden modes?','Yes, in nonminimal realizations.'),q('What can cancel hidden modes in transfer form?','Pole-zero cancellations.')],'MATLAB: minreal(sys) for transfer/state-space model simplification.',quiz('A minimal realization must be?',['Controllable and observable','Diagonal only','SISO only','Open-loop stable only'],0),'minimal')
      ]
    },
    {
      id:6,title:'Controllability & Observability',short:'C & O',level:'Advanced',icon:'C/O',
      description:'Determine whether inputs can move every state and whether sensors reveal every state, both conceptually and through rank tests.',
      lessons:[
        L('Controllability Intuition','Controllability asks: can the input influence every state direction enough to move the system where we need?','For an n-state LTI system, form the controllability matrix 𝒞=[B AB … A^{n-1}B]. Full rank n means controllable.','rank(𝒞)=n.','For A=[[0,1],[0,-2]],B=[0;1], compute [B AB] and rank.','Find controllability for A=[[0,1],[0,0]],B=[1;0].','Common mistake: checking det(A) instead of the controllability matrix.','An actuator mounted on one flexible mode may fail to influence another mode effectively.',[q('What does controllability mean physically?','Inputs can influence all state directions.'),q('What rank is required?','n, the number of states.'),q('What matrices determine controllability?','A and B.')],'MATLAB: Co=ctrb(A,B); rank(Co).',quiz('For n=3, full controllability requires rank?',['3','2','1','6'],0),'controllability','https://www.mathworks.com/videos/state-space-part-3-a-conceptual-approach-to-controllability-and-observability-1548327460100.html'),
        L('Observability Intuition','Observability asks: can we reconstruct the internal state from measured outputs over time?','Observability matrix 𝒪=[C; CA; …; CA^{n-1}]. Full rank n means observable.','rank(𝒪)=n.','For A=[[0,1],[0,-2]],C=[1,0], compute [C;CA].','Test observability when C=[0,1].','Common mistake: assuming every state must be directly measured. Observability can infer states through dynamics.','A vehicle may estimate unmeasured velocity or bias from position and other sensor histories.',[q('What matrices determine observability?','A and C.'),q('Must every state be measured directly?','No.'),q('What is full observability rank?','n.')],'MATLAB: Ob=obsv(A,C); rank(Ob).',quiz('Observability primarily concerns?',['Reconstructing states from outputs','Moving states with inputs','Choosing sample rate','Factoring polynomials'],0),'observability'),
        L('PBH Tests & Eigenvector View','Rank matrices are practical, but PBH tests connect controllability/observability directly to system modes.','A mode λ is uncontrollable if rank[λI-A, B]<n. It is unobservable if rank[[λI-A];C]<n.','PBH gives a mode-by-mode interpretation.','A mode whose left eigenvector is orthogonal to B cannot be excited by the input.','Apply PBH to a diagonal A with an input that acts only on the first state.','Common mistake: checking only one arbitrary λ instead of eigenvalues/modes of A.','Mode-by-mode insight helps actuator and sensor placement.',[q('What does PBH reveal?','Whether specific eigenmodes are controllable/observable.'),q('Which matrices are used for controllability PBH?','A, B, and eigenvalue λ.'),q('Why is mode-level insight useful?','It identifies exactly which dynamics are inaccessible.')],'MATLAB: rank([lambda*eye(n)-A B]).',quiz('PBH controllability checks rank of?',['[λI-A, B]','[A C]','B only','C only'],0),'pbh'),
        L('Decomposition & Practical Sensor/Actuator Placement','A system can contain controllable/uncontrollable and observable/unobservable subspaces. Coordinate transformations can reveal this structure.','Kalman decomposition organizes state directions by reachability and visibility. Design choices should aim to actuate important modes and sense enough information.','Minimal useful models are controllable and observable.','If a sensor measures only a decoupled state, other states may be invisible.','Given a simple three-state chain, propose better B and C placements for reachability and visibility.','Common mistake: treating rank tests as only mathematical homework rather than design feedback about actuator/sensor placement.','Robotics, aerospace, structural control, and power systems choose actuators and sensors partly to control/observe critical modes.',[q('What does Kalman decomposition separate?','Controllable/uncontrollable and observable/unobservable state subspaces.'),q('Why does actuator placement matter?','It determines which modes receive input authority.'),q('Why does sensor placement matter?','It determines which modes can be inferred from measurements.')],'MATLAB provides ctrbf/obsvf in some toolboxes and rank-based analysis tools.',quiz('Poor sensor placement can cause?',['Unobservable modes','More controllability automatically','Lower system order always','No effect'],0),'placement')
      ]
    },
    {
      id:7,title:'State Feedback & Pole Placement',short:'State Feedback',level:'Advanced',icon:'K',
      description:'Design full-state feedback, choose closed-loop poles, use Ackermann/place methods, and connect pole choices to transient specifications.',
      lessons:[
        L('Full-State Feedback Idea','State feedback replaces the input with a command that depends on the measured/estimated state.','A common control law is u=-Kx+Nr. Closed-loop state matrix becomes A-BK.','ẋ=(A-BK)x+BNr.','Changing K changes eigenvalues of A-BK when the system is controllable.','For a controllable 2-state system, derive the characteristic polynomial of A-BK.','Common mistake: using A+BK when the chosen control law is u=-Kx.','State feedback is used in aerospace, robotics, balancing systems, and high-performance motion control.',[q('What matrix determines closed-loop eigenvalues?','A-BK.'),q('What prerequisite is needed for arbitrary pole placement?','Controllability.'),q('Why use N or reference scaling?','To improve reference tracking/steady-state command scaling.')],'MATLAB: K=place(A,B,poles).',quiz('With u=-Kx, closed-loop A is?',['A-BK','A+BK','A-K','B-AK'],0),'feedbackK','https://www.mathworks.com/videos/state-space-part-2-pole-placement-1547198830727.html'),
        L('Choosing Desired Poles','Pole locations should reflect performance, actuator limits, model uncertainty, and unmodeled dynamics. Faster is not always better.','For dominant second-order poles, damping and natural frequency connect pole location to overshoot and settling time. Additional poles are often placed faster but not absurdly far left.','s=-ζωn±jωn√(1-ζ²).','Translate a 5% overshoot and 2 s settling target into an approximate pole region.','Compute ζ from overshoot formula and estimate ωn from settling time.','Common mistake: placing poles extremely far left, which can require huge control effort and amplify noise/model error.','Fast robotic motion must respect motor torque, voltage, bandwidth, and structural flexibility.',[q('Does faster pole placement always improve design?','No.'),q('What limits pole speed physically?','Actuator bandwidth/effort, noise, uncertainty, and neglected dynamics.'),q('What classical specs can guide dominant poles?','Overshoot and settling time.')],'MATLAB: place() plus step() and stepinfo() for verification.',quiz('Aggressively fast poles may cause?',['Excessive control effort','Guaranteed robustness','Zero noise sensitivity','No actuator demand'],0),'polechoice'),
        L('Ackermann’s Formula & place()','For SISO controllable systems, Ackermann’s formula gives K directly from the desired characteristic polynomial.','The controllability matrix and polynomial in A are combined to solve for K. Numerical software usually uses more robust algorithms than hand Ackermann calculations.','K=e_n^T 𝒞⁻¹ φ_d(A).','Use a 2-state system to compute K for desired poles -2 and -3.','Work the same result by coefficient matching and compare.','Common mistake: applying Ackermann when the system is not controllable.','The formula is important conceptually, while production design usually relies on robust numerical routines.',[q('What must be invertible in SISO Ackermann?','The controllability matrix.'),q('What does φ_d represent?','Desired characteristic polynomial.'),q('Why prefer place() numerically?','It is generally more robust than explicit inverse-based formulas.')],'MATLAB: acker(A,B,p) or place(A,B,p); prefer place() for numerical work.',quiz('Ackermann requires the system to be?',['Controllable','Observable only','Unstable','Diagonal'],0),'acker'),
        L('Reference Tracking & Precompensation','State feedback stabilizes dynamics, but reference tracking may need scaling or integral augmentation.','A prefilter N can set DC gain for step tracking when appropriate. Integral action can robustly eliminate constant errors under suitable conditions.','u=-Kx+Nr or augment an integrator state ξ̇=r-y.','A stable pole-placed system may settle to the wrong final value without reference scaling.','Derive N for a simple SISO state-space system with no D feedthrough.','Common mistake: assuming pole placement alone guarantees unity steady-state gain.','Servo systems require both good transient dynamics and accurate target tracking.',[q('What does reference scaling do?','Adjusts command feedforward so output reaches the desired steady value.'),q('What does integral augmentation add?','A new state integrating tracking error.'),q('Can integral action affect closed-loop order?','Yes, it adds dynamics.')],'MATLAB: compute Nbar or augment the model with an integrator and use place/lqi where appropriate.',quiz('Pole placement alone guarantees zero step tracking error?',['No','Always','Only if poles real','Only if D=1'],0),'tracking'),
        L('MIMO Pole Placement','Multi-input systems provide more design freedom but require matrix gain K and careful interpretation.','If (A,B) is controllable, eigenvalues of A-BK can be assigned within multiplicity limitations. K has one row per input.','For n states and m inputs, K is m×n.','A 4-state 2-input aircraft lateral model uses a 2×4 feedback gain.','Check matrix dimensions and discuss how actuator channels influence state feedback.','Common mistake: treating MIMO K as a scalar gain.','Flight control, multiaxis robotics, and process plants are naturally MIMO.',[q('What is K size for m inputs and n states?','m×n.'),q('What matrix gets new eigenvalues?','A-BK.'),q('Why is MIMO useful?','Multiple actuators can shape coupled modes and provide design flexibility.')],'MATLAB: place(A,B,p) supports MIMO systems subject to conditions.',quiz('For 2 inputs and 4 states, K is?',['2×4','4×2','4×4','2×2'],0),'mimo')
      ]
    },
    {
      id:8,title:'State Observers',short:'Observers',level:'Advanced',icon:'x̂',
      description:'Estimate unmeasured states, design full-order observers, understand separation principle, and connect observers to real sensor systems.',
      lessons:[
        L('Why State Estimation?','Full-state feedback needs state information, but many internal states cannot be measured directly or economically.','An observer runs a model and corrects it using measurement error.','x̂̇=A x̂+Bu+L(y-Cx̂).','If the model predicts one thing but the sensor reports another, L determines how strongly the estimate is corrected.','Explain how position measurements can help estimate velocity.','Common mistake: thinking an observer is just a low-pass filter. It uses the full dynamic model.','Vehicles estimate velocity, bias, attitude, battery state, and many internal quantities from limited sensors.',[q('What is x̂?','Estimated state.'),q('What information corrects the model estimate?','Output prediction error y-Cx̂.'),q('What matrix tunes observer correction?','L.')],'MATLAB: L=place(A\',C\',observerPoles)\'.',quiz('Observer correction uses?',['y-Cx̂','u-r','Ax only','Kx'],0),'observer'),
        L('Observer Error Dynamics','Observer design is easiest when studying estimation error e=x-x̂.','For the Luenberger observer, ė=(A-LC)e. Choose L so A-LC is stable and sufficiently fast.','ė=(A-LC)e.','Observer poles are eigenvalues of A-LC.','Derive observer error dynamics by subtracting observer equation from plant equation.','Common mistake: choosing observer poles without checking observability.','Fast estimators improve state knowledge but excessive speed can amplify measurement noise.',[q('What matrix governs estimation error?','A-LC.'),q('What condition enables arbitrary observer pole placement?','Observability.'),q('Should observer poles be infinitely fast?','No, noise and model uncertainty matter.')],'MATLAB: L=place(A\',C\',p)\'.',quiz('Observer poles are eigenvalues of?',['A-LC','A-BK','A+BK','C-A'],0),'observererror'),
        L('Separation Principle','A powerful result lets controller and observer poles be designed largely independently for an LTI system.','Combining u=-Kx̂ with an observer yields closed-loop eigenvalues that include controller poles from A-BK and observer poles from A-LC under standard assumptions.','Design K and L separately, then combine.','A controller may be designed for 2-second settling while observer poles are chosen somewhat faster.','Choose plausible controller and observer poles for a 2-state stable design.','Common mistake: making observer dynamics much too fast without considering sensor noise.','Observer-based control enables practical state-feedback implementation using limited sensors.',[q('What does separation principle allow?','Independent pole design of state feedback and observer under standard LTI assumptions.'),q('Which matrices define controller and observer poles?','A-BK and A-LC.'),q('Does estimation remove the need for a model?','No, it relies on the model.')],'MATLAB: combine estimator and controller using ss() interconnections or observer-based design workflows.',quiz('Separation principle concerns?',['Controller and observer design','Only PID tuning','Only sampling','Matrix inversion'],0),'separation'),
        L('Reduced-Order Observers & Practical Issues','If some states are directly measured, estimating all of them can be unnecessary. Reduced-order observers estimate only the unmeasured portion.','Practical estimation must address sensor noise, bias, model mismatch, and initialization.','Observer bandwidth trades speed against noise sensitivity.','If position is measured directly but velocity is not, a reduced observer may estimate velocity only.','Decide which states need estimation in a motor with measured current and speed but unknown load torque.','Common mistake: ignoring bias and noise while choosing very aggressive observer poles.','Production observers often evolve toward Kalman filters when stochastic noise modeling becomes important.',[q('Why use reduced-order observers?','To estimate only unmeasured states.'),q('What practical issue limits observer speed?','Noise and uncertainty.'),q('What advanced estimator handles noise statistically?','Kalman filter.')],'MATLAB supports estimator design and Kalman filtering through Control System Toolbox functions.',quiz('A reduced-order observer estimates?',['Only unmeasured states','Only measured states','No states','Inputs only'],0),'reducedobserver')
      ]
    },
    {
      id:9,title:'Stability & Lyapunov Methods',short:'Lyapunov',level:'Advanced',icon:'V',
      description:'Move beyond pole inspection to energy-like stability reasoning, quadratic forms, positive definiteness, and Lyapunov equations.',
      lessons:[
        L('Internal Stability & Eigenvalue Test','For continuous LTI state systems, eigenvalues of A determine internal asymptotic stability.','A is Hurwitz if every eigenvalue has negative real part. Marginal cases require more care.','ẋ=Ax stable ⇔ Re λ_i(A)<0 for asymptotic stability.','A=diag(-1,-3) is asymptotically stable; A with +0.2 eigenvalue is unstable.','Classify three given eigenvalue sets.','Common mistake: judging stability from matrix entries rather than eigenvalues.','Internal stability is essential before applying advanced control or estimation designs.',[q('What does Hurwitz mean?','All eigenvalues have strictly negative real parts.'),q('What does a positive-real-part eigenvalue imply?','Instability.'),q('Is a zero eigenvalue asymptotically stable?','No, not by the strict Hurwitz criterion.')],'MATLAB: eig(A); isstable(ss(A,B,C,D)).',quiz('A continuous A matrix is Hurwitz when?',['All eigenvalues have negative real parts','All entries are negative','det(A)>0 only','trace(A)=0'],0),'stability'),
        L('Lyapunov Stability Intuition','Lyapunov methods generalize the idea of energy decreasing over time. You do not need to solve the full trajectory to prove stability.','Choose a positive definite scalar function V(x). If V̇ is negative definite, the equilibrium is asymptotically stable under standard conditions.','V(x)>0 for x≠0; V̇(x)<0 for x≠0.','For ẋ=-ax, a>0, choose V=x²/2. Then V̇=x ẋ=-a x²<0.','Propose V for ẋ=-2x and verify.','Common mistake: showing V>0 but forgetting to evaluate V̇ along system trajectories.','Energy-based stability reasoning appears in robotics, nonlinear systems, adaptive control, and power systems.',[q('What is V analogous to?','An energy-like positive measure of distance from equilibrium.'),q('What should V̇ do for asymptotic stability?','Be negative definite.'),q('Does Lyapunov require explicit system solution?','No.')],'MATLAB symbolic tools can differentiate candidate V; numerical tools can verify matrix inequalities for LTI systems.',quiz('For asymptotic Lyapunov stability, desired V̇ is?',['Negative definite','Positive definite','Always zero','Undefined'],0),'lyapunov'),
        L('Quadratic Forms & Positive Definiteness','Quadratic Lyapunov functions turn stability into matrix conditions.','V=xᵀPx. If P>0, V is positive definite. For ẋ=Ax, V̇=xᵀ(AᵀP+PA)x.','AᵀP+PA=-Q, with Q>0.','If a positive definite P solves the Lyapunov equation for Q>0, A is Hurwitz.','For diagonal A, try diagonal P and verify signs.','Common mistake: checking only positive diagonal entries of P; positive definiteness requires stronger conditions unless special structure applies.','Quadratic energy-like functions underpin LQR, robust analysis, and many modern-control proofs.',[q('What does P>0 mean?','P is positive definite.'),q('What is a quadratic form?','xᵀPx.'),q('What equation links A,P,Q?','AᵀP+PA=-Q.')],'MATLAB: P=lyap(A\',Q) depending on equation convention; verify eig(P).',quiz('A common quadratic Lyapunov function is?',['xᵀPx','Ax+B','Cx','det(A)'],0),'quadratic'),
        L('Lyapunov Equation','The continuous Lyapunov equation provides a computational stability certificate for linear systems.','For Hurwitz A and Q>0, there exists unique P>0 satisfying AᵀP+PA=-Q.','AᵀP+PA=-Q.','Choose Q=I and solve for P numerically, then check eigenvalues of P.','Repeat for a stable 2×2 A matrix.','Common mistake: mixing the MATLAB lyap convention with a transposed equation without checking documentation.','Lyapunov equations also appear in controllability/observability Gramians and optimal control.',[q('If A is Hurwitz and Q>0, what is expected of P?','A unique positive definite solution.'),q('What does P certify?','A quadratic Lyapunov function.'),q('Where else do Lyapunov equations appear?','Gramians, LQR, filtering, and robust analysis.')],'MATLAB: P=lyap(A\',Q) or use the form matching the function definition; always verify A\'*P+P*A.',quiz('The Lyapunov equation commonly has form?',['AᵀP+PA=-Q','AP=I only','P=A+B','A-P=Q'],0),'lyapeq'),
        L('Discrete-Time Stability & Lyapunov','Digital control uses a different stability region and Lyapunov equation.','Discrete LTI stability requires eigenvalues inside unit circle. A quadratic condition uses AᵀPA-P=-Q.','AᵀPA-P=-Q.','A discrete eigenvalue 0.8 is stable, 1.05 is unstable.','Classify discrete eigenvalues and solve a scalar Lyapunov example.','Common mistake: applying continuous negative-real-part rules directly to discrete systems.','Embedded controllers must satisfy discrete-time stability after sampling and implementation.',[q('Discrete-time stable eigenvalues lie where?','Strictly inside the unit circle.'),q('What is a discrete Lyapunov form?','AᵀPA-P=-Q.'),q('Is z=-0.9 stable?','Yes, magnitude 0.9<1.')],'MATLAB: dlyap(A\',Q) with convention checks.',quiz('A discrete pole at 1.2 is?',['Unstable','Stable','Marginal because real','Always oscillatory'],0),'discrete')
      ]
    },
    {
      id:10,title:'Optimal Control / LQR',short:'LQR',level:'Advanced',icon:'J',
      description:'Learn why optimal control trades state error against control effort, how the Riccati equation appears, and how LQR gains are designed.',
      lessons:[
        L('Why Optimal Control?','Pole placement says where poles should go, but not what tradeoff is best. LQR chooses feedback by minimizing a cost that balances state size and control effort.','Define J=∫(xᵀQx+uᵀRu)dt. Q penalizes states; R penalizes control effort.','J=∫₀∞(xᵀQx+uᵀRu)dt.','Large Q on position error makes position deviations expensive; large R discourages aggressive actuator use.','For a two-state system, propose Q to penalize position more than velocity.','Common mistake: assuming larger Q always means a universally better controller. It changes tradeoffs and may demand more actuation.','LQR is used in aerospace, robotics, autonomous vehicles, balancing systems, and trajectory regulation.',[q('What does Q penalize?','State deviations.'),q('What does R penalize?','Control effort.'),q('What is LQR output?','An optimal state-feedback gain K for the chosen quadratic cost.')],'MATLAB: [K,S,e]=lqr(A,B,Q,R).',quiz('Increasing R generally encourages?',['Less control effort','More aggressive input','No change','Instability always'],0),'lqr','https://www.mathworks.com/videos/series/state-space.html'),
        L('Quadratic Cost & Weight Selection','Weights encode engineering priorities, not absolute truth. Scaling and units matter.','Q is positive semidefinite and R positive definite in standard continuous LQR assumptions. Bryson’s rule can provide a starting point using acceptable state/input magnitudes.','Example diagonal Q=diag(1/x1max²,1/x2max²), R=1/umax².','If position must stay tight but velocity can vary more, position gets larger relative weight.','Choose starter weights for x1max=0.1 m, x2max=1 m/s, umax=10 N.','Common mistake: tuning weights without inspecting resulting control effort and closed-loop poles.','Actuator saturation and state constraints make weight selection an engineering design exercise.',[q('Is LQR weight selection unique?','No.'),q('What should R satisfy?','Positive definite in standard LQR.'),q('What practical limit must be checked?','Actuator effort/saturation.')],'MATLAB: iterate Q,R and inspect eig(A-B*K), step response, and input magnitude.',quiz('In standard LQR, R should be?',['Positive definite','Zero always','Negative definite','Singular by design'],0),'weights'),
        L('Algebraic Riccati Equation','The Riccati equation is the mathematical heart of infinite-horizon LQR.','P solves AᵀP+PA-PBR⁻¹BᵀP+Q=0. Then K=R⁻¹BᵀP.','ARE: AᵀP+PA-PBR⁻¹BᵀP+Q=0.','P can be interpreted as the value-function curvature for the optimal cost.','For a scalar system, derive the scalar Riccati equation.','Common mistake: trying to solve large Riccati equations by hand instead of using reliable numerical algorithms.','Riccati equations also appear in Kalman filtering through dual estimation problems.',[q('How is K obtained from P?','K=R⁻¹BᵀP.'),q('What equation determines P?','The algebraic Riccati equation.'),q('Where else does Riccati theory appear?','Kalman filtering and optimal estimation.')],'MATLAB: care(A,B,Q,R) or lqr(A,B,Q,R).',quiz('LQR K is computed as?',['R⁻¹BᵀP','Q⁻¹A','PB only','CᵀC'],0),'riccati'),
        L('LQR Closed-Loop Interpretation','LQR still produces state feedback u=-Kx, so closed-loop dynamics are A-BK. What changes is how K was selected.','The optimal K balances cost, often producing sensible pole locations without specifying them directly.','A_cl=A-BK.','Compare pole-placement and LQR designs on the same plant and inspect state/control responses.','Design both methods and compare settling time, overshoot, and peak input.','Common mistake: claiming LQR is automatically robust to every model uncertainty. It often has useful properties, but robustness still requires analysis.','Practical teams compare performance, effort, margins, and constraints before accepting a design.',[q('What closed-loop matrix does LQR produce?','A-BK.'),q('Does LQR specify poles directly?','No, poles result from the optimization.'),q('Should actuator effort be checked?','Yes.')],'MATLAB: compare K=place(...) and K=lqr(...); simulate both.',quiz('LQR control law is commonly?',['u=-Kx','u=K only','u=Cx','u=Ax'],0),'lqrcompare'),
        L('LQI & Integral Optimal Control','LQI augments the plant with integral error and then applies quadratic optimal design.','Add an integrator state to improve constant-reference tracking or disturbance rejection under appropriate conditions.','ξ̇=r-y; augmented x_a=[x;ξ].','The augmented system is designed with lqr() or lqi() depending on workflow.','Build an augmented model for a SISO output y=Cx.','Common mistake: adding integral action without checking augmented controllability or actuator saturation.','High-accuracy servo and process applications often combine optimal state regulation with integral tracking.',[q('What does LQI add?','Integral action to an LQR-like design.'),q('What new state is common?','Integral of tracking error.'),q('What must be checked after augmentation?','Controllability and practical actuator limits.')],'MATLAB: lqi(sys,Q,R) where supported.',quiz('LQI is essentially LQR plus?',['Integral action','Derivative-only action','No feedback','Open-loop feedforward only'],0),'lqi')
      ]
    },
    {
      id:11,title:'MATLAB & Simulink Labs',short:'MATLAB Labs',level:'Lab',icon:'M',
      description:'Practice the full workflow in MATLAB and Simulink: models, responses, conversions, controllability, observers, feedback, and LQR.',
      lessons:[
        L('MATLAB Control Toolbox Basics','MATLAB is most useful when it verifies understanding rather than replacing it. Build the model by hand first, then use software to check and explore.','Core objects include tf, ss, zpk and commands such as pole, zero, step, impulse, lsim, bode, rlocus, feedback, and stepinfo.','A transfer function object stores numerator/denominator models; ss stores A,B,C,D.','G=tf(1,[1 4 3]); pole(G); step(G).','Build a first- and second-order system and compare step responses.','Common mistake: trusting plots without checking units, model coefficients, or feedback sign.','Control engineers routinely use simulation to catch design mistakes before hardware tests.',[q('What does tf() create?','A transfer-function model.'),q('What does ss() create?','A state-space model.'),q('What does stepinfo() report?','Standard transient-response metrics.')],'Lab: reproduce the mass-spring-damper example, print poles, plot step response, and explain final value.',quiz('Which command creates a state-space model?',['ss','tf2only','plot','roots'],0),'matlab'),
        L('Model Conversion & Verification','Equivalent representations should produce the same input-output behavior when initialized consistently.','Use tf2ss, ss2tf, tf(ss(...)), and compare poles and step responses.','Equivalent minimal models have the same transfer function even when A matrices differ by coordinates.','Compare a hand-derived mass-spring model to tf2ss result.','Overlay step responses and compare eigenvalues.','Common mistake: declaring conversion wrong because A matrices differ. State coordinates can differ while behavior remains equivalent.','Model conversion is routine when moving between classical analysis, modern design, and simulation tools.',[q('Do equivalent realizations need identical A matrices?','No.'),q('What should match?','Transfer behavior and poles/eigenvalues for minimal equivalent models.'),q('How can you visually verify?','Overlay responses such as step plots.')],'Lab: create both realizations, convert back to tf, compare step().',quiz('Different A matrices can still represent the same transfer function?',['Yes','No','Only if zero order','Only for unstable systems'],0),'conversion'),
        L('Controllability & Observability Lab','Rank tests become intuitive when you change B or C and watch what happens.','Use ctrb, obsv, rank, eig, and compare different actuator/sensor placements.','rank(ctrb(A,B))=n and rank(obsv(A,C))=n.','Start with a controllable/observable 2-state system, then modify B or C to break one property.','Create one uncontrollable and one unobservable variant and explain the physical meaning.','Common mistake: checking rank with exact symbolic expectations on nearly singular numerical matrices without considering tolerance.','This lab connects matrix tests to practical design decisions.',[q('Which command builds controllability matrix?','ctrb.'),q('Which builds observability matrix?','obsv.'),q('What does rank compare with?','Number of states n.')],'Lab: Co=ctrb(A,B); Ob=obsv(A,C); rank(Co); rank(Ob).',quiz('Which MATLAB function builds observability matrix?',['obsv','observe','obs','rankC'],0),'labco'),
        L('Pole Placement & Observer Lab','This lab turns state-space theory into a complete controller-estimator simulation.','Design K with place, design L using the dual system, then simulate plant plus observer.','K=place(A,B,pK); L=place(A\',C\',pL)\'.','Choose observer poles somewhat faster than controller poles, then inspect estimated vs true states.','Plot x and xhat on the same figure.','Common mistake: transposing incorrectly when using place() for observer design.','Observer-based control is a standard route from theory to implementable feedback.',[q('How is observer gain often computed with place?','L=place(A\',C\',p)\'.'),q('What should estimation error do?','Decay toward zero.'),q('Why not make observer infinitely fast?','Noise and model uncertainty.')],'Lab: build augmented plant-observer equations and compare true/estimated state traces.',quiz('Observer gain uses dual pair?',['Aᵀ,Cᵀ','A,B','C,D','B,D'],0),'labobserver'),
        L('LQR Lab','LQR is best learned by changing Q and R and observing the tradeoffs.','Compute K, closed-loop poles, state response, and required input for several weight choices.','[K,S,e]=lqr(A,B,Q,R).','Increase R and observe reduced control effort and usually slower response.','Create three designs and tabulate settling time and peak input.','Common mistake: comparing state response only while ignoring control input magnitude.','Optimization-based control is meaningful only when physical effort is part of the evaluation.',[q('What does increasing R emphasize?','Reducing control effort.'),q('What should be plotted besides output?','Control input and relevant states.'),q('What does lqr return?','Gain K and related Riccati/eigenvalue information.')],'Lab: loop over R values and store metrics.',quiz('A good LQR study compares?',['Performance and control effort','Only code length','Only eigenvector signs','Only file size'],0),'lqrlab'),
        L('Simulink Workflow','Simulink makes signal flow, nonlinear blocks, saturation, sampling, and multi-domain models visual. It should complement, not replace, equation understanding.','Build source → controller → plant → sensor/feedback. Use scopes and logging. Add saturation and disturbances deliberately.','The same equations implemented in blocks should match MATLAB LTI simulation when assumptions agree.','Build a unity-feedback second-order plant and compare Simulink step response with step(feedback(G,1)).','Add actuator saturation and observe how the nonlinear response differs.','Common mistake: leaving solver/sample-time settings inconsistent with model assumptions.','Production control development often moves from equations to simulation, code generation, and hardware testing.',[q('Why use Simulink?','Visual simulation of dynamic systems and control interconnections.'),q('What nonlinear effect is easy to add?','Actuator saturation.'),q('Why compare against MATLAB LTI result?','To verify the block model and assumptions.')],'Lab: build the closed loop, log output, compare to MATLAB response.',quiz('Which issue can make Simulink results misleading?',['Incorrect solver/sample-time settings','Using scopes','Naming signals','Adding labels'],0),'simulink')
      ]
    },
    {
      id:12,title:'Advanced Topics & Projects',short:'Advanced & Projects',level:'Expert',icon:'∞',
      description:'Extend the core into digital control, Kalman filtering, MIMO design, robustness, model predictive control, and integrative engineering projects.',
      lessons:[
        L('Digital Control Foundations','Digital control turns continuous plants and discrete computation into one closed-loop system.','Topics include sampling, zero-order hold, z-transform, discrete state-space, pole mapping, and digital implementation effects.','z=e^{sT_s} maps continuous poles to discrete poles under sampling.','A continuous pole -2 sampled at 0.1 s maps to e^{-0.2}.','Map several continuous poles and check unit-circle stability.','Common mistake: selecting sample time based only on processor convenience rather than plant bandwidth.','Embedded motor, drone, automotive, and power-electronics controllers are digital.',[q('What is the discrete stability region?','Inside the unit circle.'),q('What does zero-order hold do?','Holds actuator command constant between updates.'),q('What maps s poles to z under exact sampling?','z=e^{sT_s}.')],'MATLAB: c2d(), d2c(), pzmap(sysd).',quiz('Digital closed-loop poles should lie?',['Inside unit circle','Only left of -10','Above real axis','At z=2'],0),'digital'),
        L('Kalman Filter Introduction','A Kalman filter is an optimal linear estimator under specific stochastic assumptions. It balances model prediction against noisy measurements.','Process noise and measurement noise covariances influence the estimator gain. It is the stochastic cousin of deterministic observer design.','x_{k+1}=Ax_k+Bu_k+w_k; y_k=Cx_k+v_k.','If sensor noise grows, the filter generally trusts measurements less relative to the model.','Explain qualitatively how Q and R affect estimator behavior.','Common mistake: tuning noise covariances as arbitrary gains without understanding what they represent.','Navigation, tracking, robotics, battery estimation, and sensor fusion rely heavily on Kalman filtering.',[q('What is process noise?','Unmodeled/random disturbance affecting state evolution.'),q('What is measurement noise?','Random error in sensor outputs.'),q('What does the Kalman gain balance?','Model prediction and measurement information.')],'MATLAB: kalman(), lqe(), dlqe() depending on model form.',quiz('If measurement noise R increases greatly, the filter tends to trust?',['The model more','Measurements more','Neither model nor data','Only reference input'],0),'kalman'),
        L('MIMO Control & Interaction','In MIMO systems, one input can affect multiple outputs and loops interact. State-space methods handle this naturally.','Analyze controllability, observability, transmission behavior, decoupling, and interaction before choosing architecture.','ẋ=Ax+Bu, y=Cx+Du with vector u and y.','A quadrotor has multiple actuators affecting coupled translational and rotational motion.','Describe why tuning each loop independently may fail in a strongly coupled system.','Common mistake: treating a coupled MIMO plant as several unrelated SISO plants without checking interaction.','Aircraft, process plants, robots, and power grids are MIMO systems.',[q('What does MIMO mean?','Multiple-input, multiple-output.'),q('Why is state space natural for MIMO?','Matrix equations represent coupled inputs, states, and outputs directly.'),q('What is interaction?','One control channel influences multiple outputs/loops.')],'MATLAB: ss models and singular-value/frequency tools support MIMO analysis.',quiz('A 2-input 3-output plant is?',['MIMO','SISO','Scalar only','Open-loop by definition'],0),'mimoadvanced'),
        L('Robust Control Preview','Real models are never exact. Robust control studies performance and stability despite uncertainty.','Uncertainty may be parametric, dynamic, structured, or unstructured. Gain/phase margins are classical robustness measures; H∞ and μ methods go further.','Robust design asks what happens over a family of plants, not just one nominal model.','A motor inertia may vary with load, changing poles and required control effort.','Vary plant parameters ±20% and compare closed-loop performance.','Common mistake: validating a controller on only one nominal parameter set.','Aerospace, automotive, energy, and high-reliability systems must tolerate uncertainty.',[q('What is nominal model?','The baseline model used for design.'),q('What is robustness?','Maintaining acceptable behavior despite uncertainty.'),q('What simple classical measures reflect robustness?','Gain margin and phase margin.')],'MATLAB Robust Control Toolbox provides uncertain models and robust analysis tools.',quiz('Robust analysis should test?',['Model uncertainty','Only nominal plant','Only file format','Only input labels'],0),'robust'),
        L('Model Predictive Control Preview','MPC repeatedly solves a finite-horizon optimization problem while respecting constraints.','At each sample, predict future behavior, optimize a sequence of inputs, apply the first input, then repeat with new measurements.','min Σ cost subject to model dynamics and constraints.','MPC can directly handle actuator bounds that simple LQR does not explicitly enforce.','Explain why constraints make MPC attractive for process and vehicle applications.','Common mistake: assuming optimization can run infinitely fast; computational limits and model accuracy matter.','MPC is common in process control, automotive systems, energy, and advanced robotics.',[q('What is receding horizon?','Optimize over a future horizon, apply first move, then re-optimize next sample.'),q('Major MPC advantage?','Explicit handling of constraints.'),q('Major practical challenge?','Online computation and model quality.')],'MATLAB Model Predictive Control Toolbox supports MPC design and simulation.',quiz('MPC explicitly handles?',['Constraints','Only open-loop gain','Only eigenvectors','No model'],0),'mpc'),
        L('Capstone Project: From Physics to Modern Controller','The best way to consolidate Modern Control is to carry one physical system through the complete workflow.','Choose a motor, cart-position system, inverted pendulum, suspension, or another safe simulation plant. Derive model, validate, analyze C/O, design feedback, design observer, compare LQR, and test uncertainty.','Deliverables: equations → model → validation → controller → estimator → simulation → interpretation.','A DC motor can be modeled electrically/mechanically, converted to state space, checked for C/O, then controlled with pole placement and LQR.','Build a project plan with milestones and measurable performance targets.','Common mistake: showing plots without explaining what they prove or whether specifications were met.','This mirrors real engineering: model, analyze, design, simulate, validate, communicate.',[q('What should every project start with?','Clear physical assumptions and requirements.'),q('Why compare methods?','To understand tradeoffs rather than merely obtain one working result.'),q('What makes a project credible?','Transparent equations, verification, performance metrics, and discussion of limitations.')],'MATLAB/Simulink: create scripts that reproduce every figure and result.',quiz('A strong control project should include?',['Model validation and performance interpretation','Plots only','Code only','No assumptions'],0),'project')
      ]
    }
  ];

  const courseVideos=[
    {title:'MathWorks Control Systems Video Series',url:'https://www.mathworks.com/videos/tech-talks/controls.html',desc:'Broad control-systems video library covering feedback, PID, Bode plots, state space, LQR, Kalman filters, MPC, and more.'},
    {title:'State Space Video Series',url:'https://www.mathworks.com/videos/series/state-space.html',desc:'Intuitive state-space, pole placement, controllability/observability, and LQR videos.'},
    {title:'State-Space Models in MATLAB',url:'https://www.mathworks.com/videos/series/state-space-models-100817.html',desc:'Short practical videos on creating, analyzing, and controlling state-space models in MATLAB.'}
  ];

  return {stages,courseVideos};
})();